### ISSUE TITLE
room 에 리스트를 보여주는 기능 만들기

### ISSUE THREAD

**Issue by cwyoon-99** [qicqock/db_webserver#53]
feature/showroom
reservation.ejs와 css2/reservation_custom.css를 사용하여 
reservation 페이지를 고침
데이터를 받아와 개수에 맞게 처리해서 보여주는 게 필요

**Comment by 1004gite** [comment]
태윤이 하던 파일 이어받았습니다
feature/showroom 브랜치 따라서 작업해 보겠습니다
